#########################################################
# Gradle                                                #
#########################################################
org.gradle.jvmargs=-Xmx4G \
  --add-exports jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED \
  --add-exports jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED \
  --add-exports jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED \
  --add-exports jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED \
  --add-exports jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED

#########################################################
# Minecraft Versions                                    #
#########################################################
mc_version=1.21.1
minecraft_version=1.21.1
minecraft_version_range=[1.21,1.22)
neo_version=21.1.65
neo_version_range=[21.1,)
loader_version_range=[4,)
mod_id=avaritianerf
mod_name=AvaritiaNerf
mod_license=MIT
mod_version=1.0
mod_group_id=com.tendoarisu
mod_authors=TendoArisu
mod_description=Nerf Avaritia tools and entities.
